__author__ = 'Hooligan'

KEY_JSON_PAYLOAD = 'json_payload'
KEY_SENSORS = 'sensors'
KEY_META = 'meta'
KEY_TEMPERATURE = 'temperature'
KEY_RFID = 'rfid'
KEY_LIGHT = 'light'
KEY_VALUE = 'value'
KEY_NODE_ID = 'node_id'
KEY_NODE_STATUS = 'node_status'
KEY_LOCATION = 'location'
KEY_X_LOC = 'x'
KEY_Y_LOC = 'y'
KEY_Z_LOC = 'z'